try:
  num = int("a")

  print(num)
except ValueError as e:
  print(e)